# Generated by Django 4.1.1 on 2022-11-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="gender",),
    ]
