# Generated by Django 4.1.1 on 2022-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_orderitem_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image_url",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/img/"),
        ),
    ]
