# Generated by Django 4.1.1 on 2022-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="product_brand"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="product_category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="shop/images"),
        ),
    ]
