# Generated by Django 4.1.1 on 2022-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_brand_product_category_product_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("cart", "cart"),
                    ("waiting_for_payment", "waiting_for_payment"),
                    ("paid", "paid"),
                ],
                default="cart",
                max_length=32,
            ),
        ),
    ]
