# Generated by Django 4.1.1 on 2022-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("t-shirt", "T-SHIRT"),
                    ("sweater", "SWEATER"),
                    ("shirt", "SHIRT"),
                    ("trousers", "TROUSERS"),
                    ("jeans", "JEANS"),
                    ("outerwear", "OUTERWEAR"),
                    ("sneakers", "SNEAKERS"),
                    ("boots", "BOOTS"),
                    ("flip_flops", "FLIP_FLOPS"),
                    ("accessories", "ACCESSORIES"),
                ],
                default="sneakers",
                max_length=255,
                verbose_name="product_type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothes", "CLOTHES"),
                    ("shoes", "SHOES"),
                    ("accessories", "ACCESSORIES"),
                ],
                default="clothes",
                max_length=255,
                verbose_name="product_category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="product_code"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="product_name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
