# Generated by Django 4.1.1 on 2022-11-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_product_product_type_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothes", "CLOTHES"),
                    ("shoes", "SHOES"),
                    ("accessories", "ACCESSORIES"),
                ],
                default="shoes",
                max_length=255,
                verbose_name="product_category",
            ),
        ),
    ]
