# Generated by Django 4.1.1 on 2022-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_discount_price_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
    ]
