# Generated by Django 4.1.1 on 2022-11-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_order_amount_alter_orderitem_discount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="discount_price", new_name="old_price",
        ),
    ]
