# Generated by Django 4.1.1 on 2022-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_rename_discount_price_product_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="clothes_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("2xl", "2XL"),
                ],
                default="M",
                max_length=255,
                null=True,
                verbose_name="product_clothes_size",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="shoes_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("37", "37"),
                    ("38", "38"),
                    ("39", "39"),
                    ("40", "40"),
                    ("41", "41"),
                    ("42", "42"),
                    ("43", "43"),
                    ("44", "44"),
                ],
                default="41",
                max_length=255,
                null=True,
                verbose_name="product_shoes_size",
            ),
        ),
    ]
