# Generated by Django 4.1.1 on 2022-11-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_orderitem_clothes_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="shoes_size",),
    ]
