# Generated by Django 4.1.1 on 2022-11-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_remove_orderitem_clothes_size_orderitem_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="discount",),
    ]
