# Generated by Django 4.1.1 on 2022-12-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
    ]
