# Generated by Django 4.1.1 on 2022-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_order_delivery"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="unit",),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "MALE"), ("female", "FEMALE")],
                default="male",
                max_length=25,
                verbose_name="product_gender",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Nike", "NIKE"),
                    ("Adidas", "ADIDAS"),
                    ("Hugo Boss", "Hugo Boss"),
                    ("Zara", "Zara"),
                    ("Tommy Hilfiger", "Tommy Hilfiger"),
                    ("Calvin Klein", "Calvin Klein"),
                    ("Tommy jeans", "Tommy jeans"),
                    ("Calvin Klein Jeans", "Calvin Klein Jeans"),
                    ("Marco di radi", "Marco di radi"),
                    ("Polo Assn", "Polo Assn"),
                    ("Reebok", "Reebok"),
                    ("Polo Ralph Lauren", "Polo Ralph Lauren"),
                    ("Marco polo", "Marco polo"),
                    ("New Balance", "New Balance"),
                    ("Timberland", "Timberland"),
                    ("Nike SB", "Nike SB"),
                    ("Adidas Original", "Adidas Original"),
                    ("Dyson", "Dyson"),
                    ("H&M", "H&M"),
                    ("Massimo Dutti", "Massimo Dutti"),
                    ("Cos", "Cos"),
                    ("Jordan", "Jordan"),
                    ("Levis", "Levis"),
                    ("Sporty&rich", "Sporty&rich"),
                    ("Mango", "Mango"),
                    ("UGG", "UGG"),
                    ("Oysho", "Oysho"),
                    ("Converse", "Converse"),
                    ("Puma", "Puma"),
                    ("Crocs", "Crocs"),
                    ("The North Face", "The North Face"),
                    ("Victoria Secret", "Victoria Secret"),
                    ("The Other Stories", "The Other Stories"),
                ],
                default="Nike",
                max_length=255,
                verbose_name="product_brand",
            ),
        ),
    ]
