# Generated by Django 4.1.1 on 2022-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    (
                        "Clothes",
                        (
                            ("t-shirt", "T-SHIRT"),
                            ("shirt", "SHIRT"),
                            ("polo", "POLO"),
                            ("sweater", "SWEATER"),
                            ("hoodie", "HOODIE"),
                            ("turtleneck", "TURTLENECK"),
                            ("Longs-Leeve", "LONGSLEEVE"),
                            ("shorts", "SHORTS"),
                            ("trousers", "TROUSERS"),
                            ("jeans", "JEANS"),
                            ("sport_trousers", "SPORT_TROUSERS"),
                            ("bomber", "BOMBER"),
                            ("jacket", "JACKET"),
                            ("vest", "VEST"),
                            ("coat", "COAT"),
                            ("park", "PARK"),
                            ("down jacket", "DOWN JACKET"),
                            ("sport_costumes", "SPORT_COSTUMES"),
                        ),
                    ),
                    (
                        "Shoes",
                        (
                            ("sneakers", "SNEAKERS"),
                            ("boots", "BOOTS"),
                            ("flip_flops", "FLIP_FLOPS"),
                            ("sandals", "SANDALS"),
                        ),
                    ),
                    ("Accessories", (("accessories", "ACCESSORIES"),)),
                    ("technique", (("dyson", "DYSON"),)),
                ],
                default="sneakers",
                max_length=255,
                verbose_name="product_type",
            ),
        ),
    ]
