# Generated by Django 4.1.1 on 2022-12-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_product_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Brand")),
                ("url", models.SlugField(max_length=160, unique=True)),
            ],
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands",},
        ),
    ]
