# Generated by Django 4.1.1 on 2022-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_brands"),
    ]

    operations = [
        migrations.DeleteModel(name="Brands",),
    ]
